# Hi, this is the main config file for the project
# Variables here affect the entire site and NOT individual pages
# It's unlikely that this file will need to be edited often

website: https://dlab.berkeley.edu/
facebook: https://www.facebook.com/DLabAtBerkeley/
github: https://github.com/dlab-berkeley/
email: dlab@berkeley.edu
footer_text: Copyright © 2019 D-Lab @ UC Berkeley. All rights reserved.

# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: D-Lab Workshops
description: >- # this means to ignore newlines
  The official website for all of the workshop course material developed by D-Lab.
permalink: pretty

# DO NOT CHANGE THE DESTINATION
destination: docs

# DO NOT REMOVE THIS
collections:
  - featured

# Build settings
markdown: kramdown

# Files to be excluded from docs
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Dockerfile
